[http_server]
sockets = ["0.0.0.0:8080"]

[admin]
type = "InsecureAllowAll"

[attestation_token]
insecure_key = true
attestation_token_type = "CoCo"

[attestation_service]
type = "coco_as_builtin"
work_dir = "/opt/trustee"

  [attestation_service.attestation_token_broker]
  type = "Ear"
  policy_dir = "/etc/trustee/policies" # change to a writable diractory.

  [attestation_service.attestation_token_config]
  duration_min = 5

  [attestation_service.rvps_config]
  type = "BuiltIn"


[[plugins]]
name = "resource"
type = "LocalFs"
dir_path = "/opt/trustee/kbs-repository"
